// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pizkmnmscixczavtqiwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpemttbm1zY2l4Y3phdnRxaXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzgwNDksImV4cCI6MjA2ODg1NDA0OX0.RcaFD55l7UdcaOEfMKUYP_m5DkgCxwWxsMT1UWZvBqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});